language: python
python:
- '2.7'
cache:
  directories:
  - $HOME/.pip-cache/
  - /home/travis/virtualenv/python2.7
install:
- pip install -r requirements.txt --download-cache $HOME/.pip-cache
addons:
  postgresql: '9.2'
services:
- mongodb
- rabbitmq
before_script:
- psql -c 'create database gigwalk_apps;' -U postgres
- psql -c 'create database gigwalk_apps_test;' -U postgres
- psql -U postgres -c "create extension postgis"
- sudo su postgres -c "psql -d gigwalk_apps_test -f /usr/share/postgresql/9.3/contrib/postgis-2.1/postgis.sql"
- sudo su postgres -c "psql -d gigwalk_apps_test -f /usr/share/postgresql/9.3/contrib/postgis-2.1/spatial_ref_sys.sql"
script: py.test -v -m all

